# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test
  
  # Elegant HTTP Networking in Swift.
  pod 'Alamofire', '~> 4.8.2'
  
  pod 'SVProgressHUD' #A clean and lightweight progress HUD for your iOS and tvOS app. #https://github.com/SVProgressHUD/SVProgressHUD
  
  pod 'SwiftyJSON', '~> 4.0'
  
end
